# Generated by Django 4.2 on 2024-07-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Фильмы', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
